### ISSUE TITLE
description of the input data ml20m-all

### ISSUE THREAD

**Issue by buptqitian** [amznlabs/amazon-dsstne#11]
the dataset format:
1  2,1112486027:29,1112484676:32,1112484819:47,1112484727:50,1112484580:112,1094785740:151,1094785734:223,1112485573:253,1112484940:260,1112484826:293,1112484703:296,1112484767:318,1112484798:337,1094785709:367,1112485980:541,1112484603:589,1112485557:593,1112484661:653,1094785691:919,1094785621:924,1094785598:1009,1112486013:1036,1112485480:1079,1094785665:......

1 is the user id
2,1112486027    29,1112484676    32,1112484819:47 ...... is a pair, which 2 is movie id, and 1112486027 stands for time?

it is different from movie lens dataset in http://grouplens.org/datasets/movielens/

no ratings.

Can i say the userid 1 like movie id 2; but  not like movie 3?

Could you interpreter the dataset more detailed？

Thank you!

**Comment by rgeorgej** [comment]
Thanks for the feedback and what you mentioned is correct
1 is the userId and 2 the movieId and 1112486027 stand for time they watched

DSSTNE Engine supports analog inputs but we have not exposed it in the wrapper . if the Rating comes it could be viewed as an analog signals.

We will update the document on how to support analog Signals so that you can bring in Analog signals(Ratings) as Input to the Network

**Comment by benitezmatias** [comment]
@buptqitian, did rgeorge@ answer your question? Let me know if you need more info.

**Comment by buptqitian** [comment]
@rgeorgej @benitezmatias 
thanks a lot!
it really helps!
