### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ledrui** [amznlabs/amazon-dsstne#16]
On the example description second line :
"will go through the 3 basics steps and walk you <strike>though</strike>  _**through**_ the wrappers"

**Comment by benitezmatias** [comment]
Thank you. I've fixed the text.

**Comment by headhunters27** [comment]
Singing isn't right here I'm fucking lost! {HELP}

**Comment by rgeorgej** [comment]
@headhunters27  what kind of help do you need. Can you tell us where you were lost so that we can help you out

**Comment by headhunters27** [comment]
I'm trying to figure out what exactly is going on with my account,  because
it seems to me that either I'm forgetting everything that I've read about
and learned or I'm being hacked by somebody. Is there any details or sings
that can help me figure out if somebody had access to my e-mail and all my
account's that are connected as well? If so please tell new the steps that
I need to take.  Thanks. ..
