### ISSUE TITLE
mpiCC: No such file or directory?

### ISSUE THREAD

**Issue by llSourcell** [amznlabs/amazon-dsstne#17]
I get this error when i attemp to build the code
```

************  RELEASE mode ************
mpiCC -DOMPI_SKIP_MPICXX -std=c++0x -O3 -I/usr/local/cuda/include -IB40C -IB40C/KernelCommon -I/usr/local/include -I/usr/local/openmpi/include -I/usr/include/jsoncpp -I../utils -I../engine -c NNTypes.cpp
make[1]: mpiCC: No such file or directory
make[1]: *** [NNTypes.o] Error 1
make: *** [lib/libdsstne.a] Error 2
```

Any ideas?

**Comment by rgeorgej** [comment]
Did you install OpenMPI and updated the Path. Check https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/setup.md 

#Add the mpiCC and nvcc compiler in the path
export PATH=/usr/local/openmpi/bin:/usr/local/cuda/bin:$PATH
make
export PATH=`pwd`/bin:$PATH

**Comment by llSourcell** [comment]
Thanks! I installed that now i get this error on 'make' 

```
************  RELEASE mode ************
mpiCC -DOMPI_SKIP_MPICXX -std=c++0x -O3 -I/usr/local/cuda/include -IB40C -IB40C/KernelCommon -I/usr/local/include -I/usr/local/openmpi/include -I/usr/include/jsoncpp -I../utils -I../engine -c NNTypes.cpp
In file included from NNTypes.cpp:13:
./GpuTypes.h:30:10: fatal error: 'values.h' file not found
#include <values.h>
```

**Comment by scottlegrand** [comment]
Can you try changing

include <values.h>

to

include <limits.h>
include <float.h>

Scott

Thanks! I installed that now i get this error on 'make'

************  RELEASE mode ************
mpiCC -DOMPI_SKIP_MPICXX -std=c++0x -O3 -I/usr/local/cuda/include
-IB40C -IB40C/KernelCommon -I/usr/local/include
-I/usr/local/openmpi/include -I/usr/include/jsoncpp -I../utils
-I../engine -c NNTypes.cpp
In file included from NNTypes.cpp:13:
./GpuTypes.h:30:10: fatal error: 'values.h' file not found
#include <values.h>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/amznlabs/amazon-dsstne/issues/17#issuecomment-219849145>

**Comment by llSourcell** [comment]
i changed that now i get this error
```

************  RELEASE mode ************
mpiCC -DOMPI_SKIP_MPICXX -std=c++0x -O3 -I/usr/local/cuda/include -IB40C -IB40C/KernelCommon -I/usr/local/include -I/usr/local/openmpi/include -I/usr/include/jsoncpp -I../utils -I../engine -c NNTypes.cpp
In file included from NNTypes.cpp:14:
./NNTypes.h:25:10: fatal error: 'json/json.h' file not found
#include <json/json.h>
         ^

```

**Comment by scottlegrand** [comment]
Install libjsoncpp-dev

**Comment by llSourcell** [comment]
thx

**Comment by ibseq** [comment]
bit confused...
what the final working command?

thanks
ib
