### ISSUE TITLE
more details on SparsenessPenalty 

### ISSUE THREAD

**Issue by buptqitian** [amznlabs/amazon-dsstne#23]
in the example of recommend system's conf.josn

{
    "Version" : 0.7,
    "Name" : "AE",
    "Kind" : "FeedForward",  
    "SparsenessPenalty" : {
        "p" : 0.5,
        "beta" : 2.0
    },

    "ShuffleIndices" : false,

    "Denoising" : {
        "p" : 0.2
    },

    "ScaledMarginalCrossEntropy" : {
        "oneTarget" : 1.0,
        "zeroTarget" : 0.0,
        "oneScale" : 1.0,
        "zeroScale" : 1.0
    },
    "Layers" : [
        { "Name" : "Input", "Kind" : "Input", "N" : "auto", "DataSet" : "gl_input", "Sparse" : true },
        { "Name" : "Hidden", "Kind" : "Hidden", "Type" : "FullyConnected", "N" : 128, "Activation" : "Sigmoid", "Sparse" : true },
        { "Name" : "Output", "Kind" : "Output", "Type" : "FullyConnected", "DataSet" : "gl_output", "N" : "auto", "Activation" : "Sigmoid", "Sparse" : true }
    ],

    "ErrorFunction" : "ScaledMarginalCrossEntropy"
}

For hidden layer,:
"SparsenessPenalty" : <Boolean>             # Indicates whether sparseness penalty should be applied (default false)

So, the conf.json which defines 
"SparsenessPenalty" : {
        "p" : 0.5,
        "beta" : 2.0
    },
But in the hidden layer, SparsenessPenalty is default value (false)
Will SparsenessPenalty work or not?
And i know beta is a weight, and what about p？
Could you interpreter the neural network more detailed or give some papers?
Thank you!

**Comment by scottlegrand** [comment]
So I think that's a typo in the spec and an omission that's easily fixed in
the implementation.  "SparsenessPenalty" can be defined network-wide or
per-layer.  Defining a layer as "sparse" turns on the use of the sparseness
penalty, defaultying to the network-wide penalty if one hasn't been defined
for the layer.
i.e.

    "SparsenessPenalty" : {
        "p" : 0.5,
        "beta" : 1.0
    },


{ "Name" : "Hidden", "Kind" : "Hidden", "Type" : "FullyConnected", "Source"
: "Input", "N" : 1024, "Activation" : "Sigmoid", "Sparse" : true },

would be sparse and use the default sparseness penalty (0.5).


{ "Name" : "Hidden", "Kind" : "Hidden", "Type" : "FullyConnected", "Source"
: "Input", "N" : 1024, "Activation" : "Sigmoid", "Sparse" : true,
"SparsenessPenalty" : {
        "p" : 0.2,
        "beta" : 3.0
    }
},

would be sparse and use the layer-supplied Sparseness penalty of 0.2.

I'll submit a change this weekend to fix this.

Scott

**Comment by rgeorgej** [comment]
https://web.stanford.edu/class/cs294a/sparseAutoencoder.pdf Check from Page 14 which describes more about the Sparsness Penalty and other details

**Comment by benitezmatias** [comment]
@buptqitian , please let us know if Rejith and Scott's comments address your issue. Otherwise we'll be closing the issue in the next 48 hrs.
