### ISSUE TITLE
gtx1080 kScaleAndBias_kernel error

### ISSUE THREAD

**Issue by shyhuai** [amznlabs/amazon-dsstne#45]
Dear authors,

When I try to run the [sample](https://github.com/amznlabs/amazon-dsstne/blob/master/benchmarks/Benchmark.md) using GTX 980 card, it works properly. However, when I specified the program to GTX 1080 card on the same machine, an error was occurred as follows:

NNNetwork::NNNetwork: 1 input layer
NNNetwork::NNNetwork: 1 output layer
NNWeight::NNWeight: Allocating 115343360 bytes (2048, 14080) for weights between Input and Hidden1
Error: invalid device function launching kernel kScaleAndBias_kernel
GpuContext::Shutdown: Shutting down cuBLAS on GPU for process 0
GpuContext::Shutdown: CuBLAS shut down on GPU for process 0
GpuContext::Shutdown: Shutting down cuRand on GPU for process 0
GpuContext::Shutdown: CuRand shut down on GPU for process 0
GpuContext::Shutdown: Process 0 out of 1 finalized.

Could you help to find what it is the problem? Thank you!

Best regards,
Shaohuai

**Comment by shyhuai** [comment]
I have addressed it by compiling the source code with new arch for GTX 1080 card:
`-gencode arch=compute_61,code=sm_61`
Thank you!

**Comment by scottlegrand** [comment]
None of us have Pascal GPUs yet.  But you can probably get this to work by
changing src/amzon/dsstne/Makefile.inc line 19 from:

CU_FLAGS = -use_fast_math --ptxas-options="-v" -gencode
arch=compute_50,code=sm_50 -gencode arch=compute_30,code=sm_30
-DOMPI_SKIP_MPICXX -std=c++11
to

CU_FLAGS = -use_fast_math --ptxas-options="-v"   -gencode
arch=compute_60,code=sm_60 -gencode arch=compute_50,code=sm_50-gencode
arch=compute_50,code=sm_50 -gencode arch=compute_30,code=sm_30
-DOMPI_SKIP_MPICXX -std=c++11

DSSTNE will be updated with official support for GP1xx once GTX 1080s are
available for retail price rather than 20-40% marked up.

Also I really really wish NVIDIA had a better mechanism for detecting the
absence of of CUDA kernels for a particular GPU class, but this is the way
it works ever since Maxwell.

Scott
