### ISSUE TITLE
unit test for top k sort + sort fix

### ISSUE THREAD

**Issue by rybakov** [amznlabs/amazon-dsstne#77]
Unit test for GPU implementation of top K sort + bug fix in top K sort

**Comment by tristanpenman** [comment]
I was able to compile and run these tests using a hand-crafted build, with some minor changes to get TestSort.cpp to compile. I also found that the regular unit test build was broken due to the use of `pair` instead of `std::pair` in some of the new function templates in Utils.cpp.

Those fixes were applied as part of commit 7d57d23, so that DSSTNE continues to build and pass unit tests on Travis CI.

I should have a CMake build for GPU tests ready soon. Obviously we cannot run the GPU test suite on Travis, but it will make it easier for devs who want to run regression tests on real hardware.
