### ISSUE TITLE
Expand to multiple instances?

### ISSUE THREAD

**Issue by Ins1ghtLabs** [amznlabs/amazon-dsstne#9]
Is there a way to run this on multiple instances working on the same data set? like EMR?

**Comment by scottlegrand** [comment]
Yes, if you set up an MPI cluster, it should work.  The framework detects the lack of P2P connectivity between the GPUs in play and automagically switches to MPI system memory collectives.

However, at 10 Gb/s between g2.8xlarge instances plus ~2-3 GB/s upload/download because virtualization, you will need a rather large layer to get efficient scaling.  That said, if you just want to run large models, it *should* just work.  It has, of course, never been tried.

What will be interesting down the road is running this on RDMA-enabled servers that allow inter-system P2P copies.  That will need a few more lines of code, but it also ought to work.

**Comment by Ins1ghtLabs** [comment]
Cool, thanks! I finally can run Skynet on AWS.

**Comment by rgeorgej** [comment]
As @scottlegrand mentioned this is build on MPI from day one and you should be able to run across instances for Training.  We are working on model parallel predictions across machines

If you are using Multiple Instance please ensure that all your nodes are in the same placement group.
I would try Multiple EC2 instances on the same Placement group connected by Elastic File System so that  you can share the data across the instances

Sharing the data on HDFS with EMR will be tricky I guess

**Comment by benitezmatias** [comment]
@Ins1ghtLabs, did the responses help you? If so, I'll close this issue.

**Comment by romerocesar** [comment]
perhaps we should add this comments to the FAQ before closing this issue so other users can find it

**Comment by benitezmatias** [comment]
Added to Q&A
